Newbranchgihanesent
BC-CapstoneProjects/Socialscope pull request #106
Opened 2022-03-01 06:40 UTC by gihanen

2022-03-01 08:30 UTC, AndrewMiddletonBC requested changes

2022-03-01 08:30 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/util/Credentials.java
> +    private static final String DEFAULT_CREDENTIALS_FILE = "/Users/titie/Desktop/private/credentials.json";
Absolutely not.

2022-03-01 18:47 UTC, AndrewMiddletonBC requested changes
In the pom.xml I did not see the necessary google cloud imports from previous branches.  We cannot run this without the correct imports.

2022-03-01 18:47 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/util/Credentials.java
> -        	InputStream in = getClass().getResourceAsStream("/" + fp);
You have deleted some important lines here.  It will not work inside the jar without this.  Did you test run the jar file?

2022-03-01 18:47 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/util/Credentials.java
> -import java.io.InputStream;
Need these

2022-03-01 18:47 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/handlers/YoutubeApiHandler.java
> +   /* private String hashPoster(String poster) {
Why commented out?  It currently does not modify the string.

2022-03-01 18:47 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/handlers/YoutubeApiHandler.java
> +        if(maxResults.equals(""))
You are making this request once per video id, so it can only return one result.  Why even include the max results parameter?

2022-03-01 18:47 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/handlers/YoutubeApiHandler.java
> +                JSONObject videoData = makeQueryVideo(videoId, maxResults);
Made once per video id, I do not think maxResults does anything.

2022-03-01 18:47 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/handlers/YoutubeApiHandler.java
> +        this.limiters.add(new RateLimiter(10000, 86400000));  // 60 requests per minute; currently unimplemented
Outdated comment.

2022-03-01 18:47 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/handlers/YoutubeApiHandler.java
> +             System.out.println("Youtube access token request failed");
Deceptive print, it is a search that failed not an access token request.

2022-03-04 02:45 UTC, AndrewMiddletonBC requested changes

2022-03-04 02:45 UTC, AndrewMiddletonBC commented on root/backend/pom.xml
> +		<version>2.6.1-SNAPSHOT</version>
We cannot use this version, please revert to 2.2.0.RELEASE

2022-03-04 02:45 UTC, AndrewMiddletonBC commented on root/backend/pom.xml
> +		<java.version>17</java.version>
We need to use version 11 here, check your PR files changed for the old version.  It will not host on aws otherwise.

2022-03-04 02:45 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/handlers/RedditApiHandler.java
> +    public void requestToken(String numberOfResults) {
Don't know why this was changed back, this is the old version, requestToken should not take parameters.

2022-03-04 02:45 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/handlers/TwitterApiHandler.java
> +            this.limiters.forEach((limiter) -> {limiter.spendBudget(temp);});
Lines 40 to 50 in this version are old version please check the old file in your pull request changes section to see what to revert it too.  requestToken should not accept parameters.

2022-03-04 02:45 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/handlers/TwitterApiHandler.java
> -            this.limiters.forEach((limiter) -> {limiter.spendBudget(temp);});
This line is important.  A lot of changes you have made in twitter handler are not needed.  You should only copy over essential changes for your sentiment analysis.

2022-03-04 02:45 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/handlers/TwitterApiHandler.java
> +                requestProperties.put("User-Agent", credentials.get("user-agent"));
This will break the whole application; it reverts a fix I made.

2022-03-04 02:45 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/handlers/TwitterApiHandler.java
> +                    String text=re.getString("text");
These 3 lines and the extra exception catch on the function are the only lines I think you should be adding to this file, please check the "files changed" tab on your PR to see where other changes + accidental reverts are happening.

2022-03-04 02:45 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/util/Credentials.java
> +    public LanguageServiceSettings readGoogleCredentials() throws IOException {
I feel like this might not work inside a Jar because of file input stream specifics, but I will test it once these other changes have been made.

2022-03-04 02:45 UTC, AndrewMiddletonBC commented on root/backend/src/main/java/util/Credentials.java
> +                .setCredentialsProvider(FixedCredentialsProvider.create(ServiceAccountCredentials.fromStream(new FileInputStream(DEFAULT_CREDENTIALS_GOOGLEFILE))))
I don't see that this constant is actually declared anywhere.  Did you test run this version?

2022-03-04 03:00 UTC, thienhuynh98 requested changes
I happen the same to me, so can you make a quick change and then we can merge

2022-03-04 05:05 UTC, AndrewMiddletonBC approved these changes
Needs structural work still but at least it functions.

2022-03-04 22:27 UTC, thienhuynh98 approved these changes
Look good to me

2022-03-04 22:27 UTC, merged