Gihanehistory
BC-CapstoneProjects/Socialscope pull request #117
Opened 2022-05-04 23:43 UTC by gihanen

2022-05-05 00:26 UTC, AndrewMiddletonBC reviewed
Many of these changes are super old.  You should stash your changes, pull the latest changes in main into a new branch, and then pop your changes there, I think that will fix things.  Otherwise I have to scroll through several months worth of changes to find your work.

2022-05-05 20:11 UTC, thienhuynh98 requested changes
There are some extra files need to be removed and please use the newest version so I can run the test. Thank You!

2022-05-05 21:11 UTC, AndrewMiddletonBC requested changes

2022-05-05 21:11 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/HistoryPage.jsx
> +       <PreviewPage result={table.Results}/>
This is absolutely not how you do this.  The Preview Page is rendered using the App class, and you can use the navigate function to go there without embedding a new Preview Page or importing it.  See the search page for how to actually use navigation.

2022-05-05 21:11 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/HistoryPage.jsx
> +
Why is this all commented out?  Does it work?

2022-05-05 21:11 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/HistoryPage.jsx
> +  const [HistoryData, SetHistoryData] =  useState([]);
You will need to lift this state up to the App class, and then pass it into the results pages as props from there.  See the react documentation on lifting state up if this is unclear.

2022-05-05 21:11 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/HistoryPage.jsx
> +          onClick={() => someEventHandler} >
I tried running this but the onclick does nothing, which is not too surprising considering how you used the navigate.  Please lift the history state up the the app class.  You will also need to pass it to the Search Page and change it when the results are found there.

2022-05-05 21:11 UTC, AndrewMiddletonBC commented on root/backend/pom.xml
> +        <plugin>
What is this for?  Is there a reason you needed to add this back end dependency when you didn't change anything else in the back end?

2022-05-05 21:12 UTC, AndrewMiddletonBC commented
Please pull the changes from this branch that I added before you continue working.  I fixed the file issues this time around but I can't afford to do that every time you make a commit, so please make your branch up to date with the remote so that issue does not arise again.

2022-05-05 21:27 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/HistoryPage.jsx
> +    </div>
```suggestion
    <ContentContainer>
      <div>
        <button onClick={navigate.goBack}>Back</button>
        <p>foo</p>
      </div>
    </ContentContainer>
```

You should keep this page wrapper so that it has similar formatting to the other pages instead of a blank space.

2022-05-16 21:31 UTC, AndrewMiddletonBC requested changes

2022-05-16 21:31 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/HistoryPage.jsx
> +  const [filename, setFilesname] = useState([]);
Again, why is this all commented out?  If this is the upload / download button code it should be working right?  You should put it in a component class or inside the download page, not leave it commented out here.

2022-05-16 21:31 UTC, AndrewMiddletonBC commented on root/backend/pom.xml
> +          <artifactId>maven-surefire-plugin</artifactId>
Why is this new dependency needed?  I am still waiting for an answer.

2022-05-16 21:31 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/App.jsx
> +  const [allKeyword, setAllKeyword] =  useState([]);
Why is this spread out in 4 different state variables?  You can contain all results objects and their associated keyword and date info for the entire history array in a single object.  You can include a "selected" index as well to point to whichever history item is selected currently as well.  Then you only have to pass down a single object and setter to update all aspects of the history / results state at once.  You only ever update these objects all together anyways so why not do it in a single piece of state?

2022-05-16 21:31 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/HistoryPage.jsx
> +      data.push({ keyword:key, index:data.length, time:props.date, button: <button
You aren't using a setter for this state, breaking a fundamental principle of react.

2022-05-16 21:31 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/SearchPage.jsx
> +            setAllKeyword([...allKeyword, keyword])
Again, this should be done in a single history state object.

2022-05-16 21:31 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/HistoryPage.jsx
> +  function someEventHandler(){
You don't even update the state when this button is clicked, so the current results used in the search page will still be used.

2022-05-16 21:31 UTC, AndrewMiddletonBC commented on root/frontend/src/pages/SearchPage.jsx
>      result,
This result object was used as a placeholder before the actual history system was implemented.  You will want to get and set results from a single "history" state object, which can store an array of "result" objects and their associated keywords / dates, as well as a "selected" integer field that is the index for the currently selected "result" object in the history array that you will update when making a search and navigating the history menu.

2022-05-16 23:29 UTC, gihanen commented on root/backend/pom.xml
> +          <artifactId>maven-surefire-plugin</artifactId>
When I cloned the project to work on that, the first run I made throw a exception and when i googled it they said that I had to add that dependency

2022-05-16 23:40 UTC, gihanen commented on root/frontend/src/pages/HistoryPage.jsx
> +  const [filename, setFilesname] = useState([]);
Okay I will do it I commented them because i just wanted to see the result of history on the screen so I dont get confused

2022-05-19 07:22 UTC, closed without merging